CREATE TABLE IF NOT EXISTS document_files (
    id INT AUTO_INCREMENT PRIMARY KEY,
    folder_id INT NULL,
    file_name VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(1000) NOT NULL,
    file_size BIGINT NOT NULL,
    file_type VARCHAR(100) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_hash VARCHAR(64) NOT NULL,
    thumbnail_path VARCHAR(500) NULL,
    is_image TINYINT(1) DEFAULT 0,
    is_document TINYINT(1) DEFAULT 0,
    is_video TINYINT(1) DEFAULT 0,
    is_audio TINYINT(1) DEFAULT 0,
    uploaded_by INT NOT NULL,
    upload_ip VARCHAR(45) NULL,
    tags TEXT NULL,
    description TEXT NULL,
    is_favorite TINYINT(1) DEFAULT 0,
    is_public TINYINT(1) DEFAULT 0,
    download_count INT DEFAULT 0,
    last_accessed TIMESTAMP NULL,
    is_deleted TINYINT(1) DEFAULT 0,
    deleted_at TIMESTAMP NULL,
    deleted_by INT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_folder (folder_id),
    KEY idx_file_type (file_type),
    KEY idx_uploaded_by (uploaded_by),
    KEY idx_deleted (is_deleted),
    FULLTEXT KEY idx_search (file_name, original_name, tags, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;